trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Trivy"
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  displayName: 'Install Trivy'

- script: |
    echo "Scanning the Docker image with Trivy"
    trivy image --severity HIGH,CRITICAL nginx:latest
  displayName: 'Run Trivy Scan'