name: Horusec Scan

on: [push]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    env: 
      Author: "doiteasy02@gmail.com"
      HORUSEC_CLI_RETURN_ERROR_IF_FOUND_VULNERABILITY: "false"
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./
